### PR TITLE
Replace Contributing docs with link to Pelican docs

### LINKED ISSUE #4: Move contributing guidelines to Pelican docs
As it stands, this template includes identical, very detailed contributing guidelines into every plugin created with it. Wouldn't those guidelines be easier to maintain in the pelican docs (with a link in the plugin readme)?

### PR DESCRIPTION
**Pull request by justinmayer**
As per the discussion about moving contributing guidelines to Pelican docs. Fixes #4

### CODE REVIEW

**Comment by justinmayer** [comment]
@oulenz @davidag @avaris: How does this look?

**Review by davidag — APPROVED** [review]

**Comment by oulenz** [comment]
Is there a particular reason why you didn't put this in the readme? Now the readme sends users to this file, which sends them on to the documentation.

Otherwise it looks good to me!

**Comment by justinmayer** [comment]
@oulenz: Oops. Thank you for pointing that out. I have added the same link and verbiage to the README via b691a86. Yes, that means the same information is replicated in both README and CONTRIBUTING, but I think that is necessary in order to benefit from [GitHub's CONTRIBUTING file integration](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors). Does that seem like an adequate solution?

**Comment by oulenz** [comment]
Ah yes, I suspected there might be a good reason to have a separate CONTRIBUTING file.

This seems fine now (unless we can figure out a way to automatically transclude CONTRIBUTING into the readme).

**Comment by justinmayer** [comment]
> (unless we can figure out a way to automatically transclude CONTRIBUTING into the readme)

I considered that, but [GitHub does not support it](https://github.com/github/markup/issues/172#issuecomment-33241601) — not for Markdown, reStructuredText, or any other markup format.

**Review by avaris — APPROVED** [review]

**Comment by justinmayer** [comment]
@oulenz @davidag @avaris: Many thanks for reviewing!

**Pull request merged**
